<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="presentation.css">
    <title>Presentation</title>
</head>
<body>
    <div class="presentation-container">
        <h1>Study on the Acoustic Emanations of Keyboards</h1>
        <p>
            The acoustic emanations generated by electronic devices have long been a concern within the security and privacy communities. These emanations, whether electromagnetic, optical, or acoustic, have been exploited as potential sources for attacks. Researchers have demonstrated the possibility of retrieving sensitive information from the acoustic emanations produced by keyboards during typing. For instance, Asonov and Agrawal successfully recovered text by analyzing the acoustic emanations resulting from keyboard typing. These attacks raise privacy concerns, especially in a world where computing and new technologies are increasingly prevalent, particularly with the widespread adoption of telecommuting.
        </p>
        <p>
            As part of our second-year engineering studies in computer science at ENSICAEN, our team was presented with a project by the GREYC research laboratory. The project was structured around two main axes. The first aimed to identify an individual solely based on the sounds emitted during keyboard typing, while the second sought to decode the text typed by a person based solely on the noises produced during this operation. The results of our experiments, utilizing a database of keyboard typing recordings that we created, underscore the potential risks associated with the sounds produced during this activity.
        </p>
        <p>
            In a context where computing plays a central role in contemporary society, this research domain holds particular significance. Beyond its implications for the general public, these advancements could also find applications in contexts such as criminal investigations, where recovering the sound emitted by a suspect's keyboard could provide crucial information. This study outlines how our approach, utilizing machine learning techniques, addresses the objectives of the project.
        </p>
        <a href="../menu.php">Discover more</a>
    </div>
</body>
</html>
